x = input('Digite algo na tela: ')
letra = x.isalpha()
numero = x.isnumeric()
alpha = x.isalnum()
space = x.isspace()
type = type(x)
mai = x.isupper()
min = x.islower()
cap = x.istitle()
print('Qual a classe do caracter digitado? {}'.format(type))
print('É somente letra? {}'.format(letra))
print('É somente número? {}'.format(numero))
print('É alfanumérico? {}'.format(alpha))
print('É somente espaço? {}'.format(space))
print('É maiúsculo? {}'.format(mai))
print('É minúsculo? {}'.format(min))
print('Tem a primeira letra escrita em maiúsculo? {}'.format(cap))
